---
name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: npm install
        shell: bash
        run: |
          npm install
          npm install -g oclif
      - name: build
        shell: bash
        run: |
          npm run build
          oclif pack macos
          oclif pack tarballs
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: github-actions
          aws-region: us-east-1
      - name: deploy
        shell: bash
        run: |
          version=$(node -p "require('./package.json').version")
          oclif upload macos
          oclif upload tarballs
          oclif promote --channel=stable --version="${version}" -m --indexes --sha="${GITHUB_SHA::7}"
      - name: github release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/*.tgz
            ./dist/*.pkg
          token: ${{ secrets.GITHUB_TOKEN }}
